### ISSUE TITLE
file extension

### ISSUE THREAD

**Issue by thorr18** [CanDKD/SV_Multi_Search#1]
I'm not sure most users know what to do when following your URL to https://github.com/CanDKD/SV_Multi_Search/blob/master/SVENMultiSearch

It just displays code, meaning nothing to most. Even going to the raw link won't actually serve a working search tool: 
https://raw.githubusercontent.com/CanDKD/SV_Multi_Search/master/SVENMultiSearch

Even after exploring github until finding a download option, many wouldn't know what to do with the file after downloading. Perhaps adding an extension of .html to the filename would make it so more people's systems would know what to do with the file.

**Comment by CanDKD** [comment]
thorr18,  Thank you for your comments.  I will add a 'Read Me' file to my
GitHub and include those instructions on the Duolingo comment.

**Comment by CanDKD** [comment]
thorr18, I have added details for accessing and saving the tool in the ReadMe file.  I hope this is clearer now.  Thank you for taking the time to comment and for suggesting improvements.  Candace

**Comment by thorr18** [comment]
Now I can right-click on the following URL, "save link as" and open the file without any renaming. 
https://github.com/CanDKD/SV_Multi_Search/raw/master/SVENMultiSearch.html

**Comment by CanDKD** [comment]
thorr18, thank you for your comment.  I have added instructions to add the
SVENMultiSearch file to the Pop Up Blocker exceptions list.  I still need
to figure out how to set up Microsoft IE and Edge so the tool works in
those browsers.
​
Candace​
