### ISSUE TITLE
pop up instructions wrong in readme

### ISSUE THREAD

**Issue by thorr18** [CanDKD/SV_Multi_Search#2]
Using the default setting in Chrome blocks the multi search windows, but the readme said this is only for IE. 
I set the downloaded file to allow future pop ups: 
<img width="887" alt="popupschrome" src="https://cloud.githubusercontent.com/assets/3753521/22204129/62c14a70-e13e-11e6-87c5-fbb65997de75.png">

**Comment by CanDKD** [comment]
I have edited the 'Read Me' file to include instructions to add the SVENMultiSearch file to the Pop Up Blocker exceptions list.  That is easy enough to do for Chrome and Firefox but I still have to figure out how to do this in MS IE and MS Edge.  Thanks again for improving access to this code.
